### ISSUE TITLE
explorerlink.py not correctly returning analog inputs

### ISSUE THREAD

**Issue by predrag-viceic** [pimoroni/node-red-nodes#1]
Hello,

First of all, thanks for the node-red libraries !

I have stumbled upon a problem in the explorerlink.py, as when I connect a wire from on explorer hat from +5v to analog 1,   I should get ~5 output as analog.0 only, but I receive below kind of streams. As if all the values are sent for all the topics.

**analog.3:4.857**
analog.2:0.588
analog.3:0.597
analog.0:0.579
analog.1:0.579
**analog.2:4.875**
analog.3:4.875
analog.2:0.693
analog.3:0.606
analog.2:0.591
**analog.1:4.872**
**analog.3:4.899**

Do I understand correctly ?

Thanks for your help,
Predrag

**Comment by Gadgetoid** [comment]
The values from other channels are likely to be random noise/electronic interference that just happens to exceed the threshold for being reported. The one thing that is confusing is the `analog.0:0.579` report in there. If it's tied to 5v it should be the one signal that's totally stable and goes unreported since it wont generate a change event.

At the moment analog values are read in tern, and when one changes by more than 0.01v it's passed to the change handler. This then passes that value on if it's been more than 1 second since the last change. This is something I need to tweak anyway since it doesn't make a lot of sense to rate-limit on _both_ change amount and time.

**Comment by predrag-viceic** [comment]
What puzzles me, is that I'm getting periodically ~5v on **all** the inputs, but only one is connected.

This makes me think that something is wierd with the value selection / storage

**Comment by Gadgetoid** [comment]
It's quite possible that since the other ADC channels are floating, the 5v in one could induce the same voltage on the others. This happens fairly predictably with Enviro pHAT for example. I'm not sure if it's occurring within the ADC or on the traces/pads outside, but it's a very confusing thing to run into for the first time :D

One of my planned changes for Explorer HAT is to break it down into individual channels, so you can, for example, just watch "ADC Channel 1" and not get all the noise from the others. I think this is a more sensible approach, but I ran into some trouble (Arrrghhh NodeJS) getting it up and running.

It's clear the "on change" trigger is possibly not ideal for watching the analog inputs, I think a rate-limited, streaming ADC value might make more sense.

**Comment by predrag-viceic** [comment]
Cool, looking forward for the rewrite. I think that my board is broken because even with  analog1 at 5v and analog2,3,4 grounded, I'm getting this with ./analog-event.py:

('one', 0.0)
('one', 4.89)
('one', 0.0)
('one', 4.878)
('one', 0.0)
('one', 4.914)
('one', 0.0)
('one', 4.902)
('one', 0.0)
('one', 4.872)
('one', 0.0)
('one', 4.923)
('one', 0.0)
('one', 4.89)
('one', 0.0)
('one', 4.926)

**Comment by predrag-viceic** [comment]
Ok, this worked well for me:

``` python
class AnalogReader (Thread):
    def __init__(self):
        super(AnalogReader, self).__init__();
        self.daemon = True;
    def run(self):
        while (True):
            emit("analog.{}:{}".format(0,explorerhat.analog.one.read()));
            emit("analog.{}:{}".format(1,explorerhat.analog.two.read()));
            emit("analog.{}:{}".format(2,explorerhat.analog.three.read()));
            emit("analog.{}:{}".format(3,explorerhat.analog.four.read()));
            time.sleep(0.5);

if explorerhat.has_analog:
    AnalogReader().start();
```

I don't think having change detection on the node level is really needed, as the data can be filtered further with the RBE node if needed, or smoothed, ratelimited etc directly in the flow. What would however be usefull is having the frequency parameter (Hz) which would be used to calculate the Thread sleep time.

**Comment by janeksz** [comment]
Hi,
I'm trying to use analog reading on Node_RED and it returns erratic values,
for example +3.3V connected to AIN1 gives outputs as per screenshot below.
What is the fix?
![ehaterraticanalog](https://user-images.githubusercontent.com/10751584/29649704-2aecea12-88d9-11e7-8161-240504bec947.png)

**Comment by janeksz** [comment]
@Gadgetoid will you be kind to give a hint on possible solution?

**Comment by janeksz** [comment]
@predrag-viceic where is located the script you modified? Does it work ok now for you?

**Comment by Gadgetoid** [comment]
@predrag-viceic is it possible you could submit your solution as a pull-request? It would be much appreciated.

Sorry for appearing to abandon this thread- I did not manage to set up another working dev environment for Node-RED. Unfortunately it seems to be a little bit complicated to keep ahead of Node's fast-paced ecosystem for a casual node user.

**Comment by Gadgetoid** [comment]
Closed for now since I wont be able to make any progress on this. But by all means re-open if there are any further developments.
